@baseUrl = http://localhost:3002/api
@contentType = application/json

@auth = {{login.response.body.$.token}}

### 👉 User Login

# @name login
@adminuserid = {{login.response.body.id}}
POST {{baseUrl}}/users/login
Content-Type: {{contentType}}

{
  "email": "wcj@admin.com",
  "password": "1234"
}

### 👉 Get Password

GET {{baseUrl}}/passwords?token={{auth}}
Content-Type: application/json

### 👉 Get One Password

GET {{baseUrl}}/passwords/2
Content-Type: application/json
Authorization: token {{auth}}

### 👉 Decrypt One Password

POST {{baseUrl}}/passwords/144/decrypt
Content-Type: application/json
Authorization: token {{auth}}

### 👉 Create Password

POST {{baseUrl}}/passwords
Content-Type: {{contentType}}
Authorization: token {{auth}}

{
  "title": "title {{$randomInt 1 1200}}",
  "username": "wcj{{$randomInt 1 1200}}",
  "password": "12345",
  "url": "http://github.com/jaywcjlove",
  "notes": "This is a test note {{$randomInt 1 1200}}"
}

### 👉 Delete One Password

DELETE {{baseUrl}}/passwords/7
Content-Type: application/json
Authorization: token {{auth}}

### 👉 Modify One Password

PUT {{baseUrl}}/passwords/4
Content-Type: application/json
Authorization: token {{auth}}

{
  "title": "title {{$randomInt 1 1200}}",
  "password": "123",
  "url": "http://github.com/jaywcjlove/{{$randomInt 1 1200}}",
  "notes": "This is a test note {{$randomInt 1 1200}}"
}
